### ISSUE TITLE
Newest version of postgresql and sequelize don't seem to be compatible.

### ISSUE THREAD

**Issue by jfaganUK** [jfaganUK/openeddi3#3]

**Comment by jfaganUK** [comment]
What I've had to do is edit the pg_hdb.conf and change the _md5_ password authentication to _password_. That allowed the user to authenticate.

**Comment by jfaganUK** [comment]
Currently experiencing this error

```
Unhandled rejection SequelizeBaseError: unrecognized configuration parameter "autocommit"
    at Query.module.exports.Query.formatError (/home/jfagan/Dropbox/projects/openeddi/openeddi3/node_modules/sequelize/lib/dialects/postgres/query.js:421:16)
    at Query.<anonymous> (/home/jfagan/Dropbox/projects/openeddi/openeddi3/node_modules/sequelize/lib/dialects/postgres/query.js:105:21)
    at emitOne (events.js:96:13)
    at Query.emit (events.js:188:7)
    at Query.handleError (/home/jfagan/Dropbox/projects/openeddi/openeddi3/node_modules/pg/lib/query.js:99:8)
    at Connection.<anonymous> (/home/jfagan/Dropbox/projects/openeddi/openeddi3/node_modules/pg/lib/client.js:166:26)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:188:7)
    at Socket.<anonymous> (/home/jfagan/Dropbox/projects/openeddi/openeddi3/node_modules/pg/lib/connection.js:109:12)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```

**Comment by jfaganUK** [comment]
Previous problem solved by updating sequelize to 3.30.

New problem:

```
27 Jan 09:40:22 - [db] Unable to connect to the database: Error: A column called 'id' was added to the attributes of 'appstate' but not marked with 'primaryKey: true'
    at Model.addDefaultAttributes (/home/jfagan/Dropbox/projects/openeddi/openeddi3/node_modules/sequelize/lib/model.js:177:13)
    at Model.init (/home/jfagan/Dropbox/projects/openeddi/openeddi3/node_modules/sequelize/lib/model.js:703:24)
    at Sequelize.define (/home/jfagan/Dropbox/projects/openeddi/openeddi3/node_modules/sequelize/lib/sequelize.js:632:17)
    at Object.<anonymous> (/home/jfagan/Dropbox/projects/openeddi/openeddi3/oe/oe_server/db/models/appstate.js:11:26)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/jfagan/Dropbox/projects/openeddi/openeddi3/oe/oe_server/db/models/_list.js:9:20)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```
