### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by r76941156** [jfaganUK/openeddi3#4]
Hi,

Do you know how to fix below issue:

"2 Mar 17:08:25 - [prepareSession] Creating the session store
Possibly unhandled SequelizeBaseError: unrecognized configuration parameter "autocommit"
    at Query.module.exports.Query.formatError (/var/www/html/openeddi3/node_modules/sequelize/lib/dialects/postgres/query.js:419:16)
    at Query.<anonymous> (/var/www/html/openeddi3/node_modules/sequelize/lib/dialects/postgres/query.js:106:21)
    at emitOne (events.js:96:13)
    at Query.emit (events.js:188:7)
    at Query.handleError (/var/www/html/openeddi3/node_modules/pg/lib/query.js:99:8)
    at Connection.<anonymous> (/var/www/html/openeddi3/node_modules/pg/lib/client.js:166:26)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:188:7)
    at Socket.<anonymous> (/var/www/html/openeddi3/node_modules/pg/lib/connection.js:109:12)
    at emitOne (events.js:96:13)
Possibly unhandled SequelizeBaseError: unrecognized configuration parameter "autocommit"
..........

**Comment by r76941156** [comment]
I try to modify 'method' from 'trust' to password from /etc/postgresql/9.*/main/pg_hba.conf. But, it did not work.

**Comment by jfaganUK** [comment]
The problem stems from conflicts from an older version of Sequelize and the newest version of Postgres. I am currently working on updating the software to work with the latest Sequelize and Postgres.

Right now the quickest solution is to install the *previous* version of Postgres. I think you're safest with 9.3. Here are my current installation notes:

- Install Nodejs, I used the nvm approach
- Testing with Node version 6.4.0
- Install postgresql ~9.3.x
  - https://www.postgresql.org/download/linux/ubuntu/
- Install npm, screen, git using apt
- Install bower
- Clone openeddi
- Npm install
- ```cd oe & bower install```
- Setup postgres some more
  - ```sudo vim /etc/postgresql/9.3/main/pg_hba.conf```
  - Line 92 should be this (change md5 to password):
  - ```host    all             all             127.0.0.1/32            password```
  - ```sudo /etc/init.d/postgresql restart```

**Comment by jfaganUK** [comment]
#3

**Comment by r76941156** [comment]
Thanks. But, I got a new error:

"3 Mar 11:03:02 - [prepareSession] Creating the session store
/var/www/html/openeddi3/oe/oe_server/create_app.js:116
if (OEConfig.build.minify) {
                  ^

TypeError: Cannot read property 'minify' of undefined
    at Object.<anonymous> (/var/www/html/openeddi3/oe/oe_server/create_app.js:116:19)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at getExpressApp (/var/www/html/openeddi3/server.js:54:11)
    at /var/www/html/openeddi3/node_modules/async/lib/async.js:699:13
"

**Comment by jfaganUK** [comment]
@r76941156 What does your ```config.json``` look like?

**Comment by r76941156** [comment]
It works now. I will let you know if I have ANY questions. Thanks.
